spring:
  profiles:
    include: default
  datasource:
    url: ${JDBC_DATABASE_URL}?createDatabaseIfNotExist=true&useSSL=false&amp&autoReconnect=true&useLegacyDatetimeCode=false
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
