spring:
  profiles:
    include: default
  datasource:
    url: jdbc:postgresql://postgres:1111@localhost:3367/postgres?createDatabaseIfNotExist=true&useSSL=false&amp&autoReconnect=true&useLegacyDatetimeCode=false
    username: postgres
    password: 1111