server:
  port: ${PORT:8087}
spring:
  datasource:
    initialization-mode: always
  jackson:
    mapper:
      DEFAULT_VIEW_INCLUSION: true
  jpa:
    properties:
      connection:
        characterEncoding: utf-8
        CharSet: utf-8
        useUniCode: true
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 2738450083069231
            clientSecret: d886b432f8f5af1fe9a7f6263593dfab
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - email
              - public_profile
          google:
            clientId: 1078423737274-5usbl5lv8f7e43n903ikmrj9l00nu068.apps.googleusercontent.com
            clientSecret: ER7oyL2GUqfA2usa8z6OQyAS
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope:
              - email
              - profile
          github:
            clientId: 924d3fae61ca90bad6c5
            clientSecret: 0848d9a26e76072a0e87799a7fff55443a7ea07f
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
app:
  auth:
    tokenExpirationMsec: 864000000
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  oauth2:
    authorizedRedirectUris:
      - https://kos-todo.herokuapp.com/oauth2/redirect
      - http://localhost:9292/oauth2/redirect
      - http://localhost:8080/oauth2/redirect
      - http://localhost:80/oauth2/redirect
      - http://localhost/oauth2/redirect
